/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2025-01-13 02:28:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class NewFile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/csj97/tomcat/lib/jstl-1.2.jar", Long.valueOf(1734052058125L));
    _jspx_dependants.put("jar:file:/C:/csj97/tomcat/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* 전체 글꼴과 배경 */\r\n");
      out.write("body {\r\n");
      out.write("    font-family: 'Noto Sans KR', sans-serif; /* 고딕 계열 폰트 */\r\n");
      out.write("    background-color: #ffffff; /* 하얀 배경 */\r\n");
      out.write("    color: #000000; /* 검정 글씨 */\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 컨테이너 */\r\n");
      out.write(".container {\r\n");
      out.write("    max-width: 1100px; /* 가로 최대 넓이를 약간 줄임 */\r\n");
      out.write("    margin: 0 auto; /* 중앙 정렬 */\r\n");
      out.write("    padding: 0 20px; /* 양옆 여백 조정 */\r\n");
      out.write("    box-sizing: border-box; /* 패딩 포함 크기 계산 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 공통 설정 */\r\n");
      out.write("div {\r\n");
      out.write("    border: 1px solid #e0e0e0; /* 부드러운 테두리 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 헤더 */\r\n");
      out.write(".header {\r\n");
      out.write("    width: 100%; /* 가로 길이 꽉 채움 */\r\n");
      out.write("    height: 80px; /* 높이 조정 */\r\n");
      out.write("    background-color: #000000; /* 검정 배경 */\r\n");
      out.write("    color: #ffffff; /* 하얀 글씨 */\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    font-size: 22px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 네비게이션 */\r\n");
      out.write(".nav {\r\n");
      out.write("    width: 100%; /* 가로 길이 꽉 채움 */\r\n");
      out.write("    height: 60px; /* 높이 조정 */\r\n");
      out.write("    background-color: #f8f8f8; /* 연한 회색 배경 */\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    color: #000000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 메인 콘텐츠 */\r\n");
      out.write(".content {\r\n");
      out.write("    margin: 20px 0;\r\n");
      out.write("    padding: 20px 0;\r\n");
      out.write("    border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 프로필 */\r\n");
      out.write(".profile-field {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    margin: 15px 0; /* 마진 축소 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile-circle img {\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    width: 100px; /* 이미지 크기 축소 */\r\n");
      out.write("    height: 100px;\r\n");
      out.write("    border: 2px solid #000000; /* 검정 테두리 */\r\n");
      out.write("    margin-left: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile-field span h2 {\r\n");
      out.write("    color: #000000;\r\n");
      out.write("    font-size: 18px; /* 텍스트 크기 축소 */\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"button\"] {\r\n");
      out.write("    background-color: #000000; /* 검정 버튼 */\r\n");
      out.write("    color: #ffffff; /* 하얀 글씨 */\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding: 6px 12px; /* 크기 축소 */\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"button\"]:hover {\r\n");
      out.write("    background-color: #333333; /* 어두운 회색 배경 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 리뷰 */\r\n");
      out.write(".review-list {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between; /* \"더보기\"와 제목 정렬 */\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".review-list h2 {\r\n");
      out.write("    font-size: 16px; /* 텍스트 크기 축소 */\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".review-list h3 a {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: #000000; /* 검정 링크 */\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".review-list h3 a:hover {\r\n");
      out.write("    color: #555555; /* hover 시 회색 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".review-comment {\r\n");
      out.write("    font-size: 12px; /* 텍스트 크기 축소 */\r\n");
      out.write("    color: #4f4f4f; /* 어두운 회색 글씨 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 예약 리스트 */\r\n");
      out.write(".reservation-list {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between; /* 제목과 더보기 정렬 */\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reservation-list h2 {\r\n");
      out.write("    font-size: 16px; /* 텍스트 크기 축소 */\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reservation-list h3 a {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: #000000; /* 검정 링크 */\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reservation-list h3 a:hover {\r\n");
      out.write("    color: #555555; /* hover 시 회색 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 예약한 가게 */\r\n");
      out.write(".reserv-place-list-field {\r\n");
      out.write("    display: flex; /* 수평 정렬 */\r\n");
      out.write("    gap: 15px; /* 카드 사이 간격 축소 */\r\n");
      out.write("    overflow-x: auto; /* 가로 스크롤 가능 */\r\n");
      out.write("    padding-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reserv-place-list {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    flex: 0 0 18%; /* 카드 크기 축소 */\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reserv-place-list img {\r\n");
      out.write("    border-radius: 5px; /* 부드러운 모서리 */\r\n");
      out.write("    border: 1px solid #e0e0e0;\r\n");
      out.write("    width: 100%; /* 부모 컨테이너에 맞춤 */\r\n");
      out.write("    height: auto; /* 비율 유지 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reserv-place-list h2, .reserv-place-list h3 {\r\n");
      out.write("    color: #000000;\r\n");
      out.write("    font-size: 14px; /* 텍스트 크기 축소 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 좋아요 리스트 */\r\n");
      out.write(".like-list {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between; /* 제목과 더보기 정렬 */\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".like-list h2 {\r\n");
      out.write("    font-size: 16px; /* 텍스트 크기 축소 */\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".like-list h3 a {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: #000000; /* 검정 링크 */\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".like-list h3 a:hover {\r\n");
      out.write("    color: #555555; /* hover 시 회색 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 좋아요한 가게 */\r\n");
      out.write(".like-place-list-field {\r\n");
      out.write("    display: flex; /* 수평 정렬 */\r\n");
      out.write("    gap: 15px; /* 카드 사이 간격 축소 */\r\n");
      out.write("    overflow-x: auto; /* 가로 스크롤 가능 */\r\n");
      out.write("    padding-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".like-place-list {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    flex: 0 0 18%; /* 카드 크기 축소 */\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".like-place-list img {\r\n");
      out.write("    border-radius: 5px; /* 부드러운 모서리 */\r\n");
      out.write("    border: 1px solid #e0e0e0;\r\n");
      out.write("    width: 100%; /* 부모 컨테이너에 맞춤 */\r\n");
      out.write("    height: auto; /* 비율 유지 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".like-place-list h2 {\r\n");
      out.write("    color: #000000;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    font-size: 14px; /* 텍스트 크기 축소 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 푸터 */\r\n");
      out.write(".footer {\r\n");
      out.write("    width: 100%; /* 가로 길이 꽉 채움 */\r\n");
      out.write("    height: 120px; /* 높이 축소 */\r\n");
      out.write("    background-color: #000000; /* 검정 배경 */\r\n");
      out.write("    color: #ffffff; /* 하얀 글씨 */\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"header\">header</div>\r\n");
      out.write("		<div class=\"nav\">nav</div>\r\n");
      out.write("		<div class=\"content\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"mypage\" style=\"border: none;\">\r\n");
      out.write("				<h1>MyPage</h1>\r\n");
      out.write("				<h2>내 프로필</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("			<hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"profile\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"profile-field\" style=\"border: none;\">\r\n");
      out.write("					<div class=\"profile-circle\" style=\"border: none;\">\r\n");
      out.write("						<img\r\n");
      out.write("							src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpgDevrlkGRc_wQ5fcoY3WZPh42yBUJhVPNA&s\"\r\n");
      out.write("							alt=\"profile-img\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"border: none; align-content: baseline;  margin-left: 30px; margin-bottom: 10px;\">\r\n");
      out.write("					<span>\r\n");
      out.write("						<h2>대식가 비숑(ID) 님 (🖐🏻'-' )</h2> 00 러버 비숑 님, 오늘은 어떤 맛집을 찾아볼까요? 🍫͜\r\n");
      out.write("						(ᵔ ̮ ᵔ)›\r\n");
      out.write("					</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"border: none; margin-left: -185px;\r\n");
      out.write("    margin-top: -30px; align-content: center;\" >\r\n");
      out.write("							<input type=\"button\" value=\"프로필 수정\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<br> <br>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"review-list\" style=\"border: none;\">\r\n");
      out.write("				<h2 style=\"margin-inline-end: auto;\">작성한 맛리뷰</h2>\r\n");
      out.write("				<div style=\"border: none;\">\r\n");
      out.write("					<h3> <a href=\"http://localhost/18_KHH_Test/ReviewsPage.jsp\" > 더보기 ></a></h3>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<hr>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"review-comment\" style=\"border: none;\">\r\n");
      out.write("				<span>🦀🍴</span> [ 맛리뷰 예시 ] 가게명 / 제목 or 텍스트 일부 / 게시일\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"review-comment\" style=\"border: none;\">\r\n");
      out.write("				<span>🦀🍴</span> 홋카이도넘버원 (北海道ナンバーワン) | 찾았습니다. 존맛탱 홍게집....! 홍게 속살이 꽉\r\n");
      out.write("				차있는 숨은 골목 .. | 2025.01.10\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"review-comment\" style=\"border: none;\">\r\n");
      out.write("				<span>🦀🍴</span> 우유빙수 (ミルクかき氷) | 산처럼 쌓인 우유 빙수가 인상적인 디저트 맛집입니다. 만족만족\r\n");
      out.write("				대만족! | 2025.01.10\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<br> <br>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"reservation-list\" style=\"border: none;\">\r\n");
      out.write("				<h2 style=\"margin-inline-end: auto;\">예약한 가게</h2>\r\n");
      out.write("				<div style=\"border: none;\">\r\n");
      out.write("					<h3> <a href=\"http://localhost/18_KHH_Test/ReservationPage.jsp\"> 더보기 > </a></h3>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<hr>\r\n");
      out.write("			<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"reserv-place-list-field\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"reserv-place-list\">\r\n");
      out.write("					<img\r\n");
      out.write("						src=\"https://mblogthumb-phinf.pstatic.net/MjAxODA3MDVfNDAg/MDAxNTMwNzU3MjEyNjQ0.RNprD67cJ2AOWI2GmRVprWVv7qtNI-d3WsN-XhRLTLIg.hpd6lxFA6mkoZ-78fN-zmiLtxAv9H3iP_Jxs6bF7XCEg.PNG.witchstudio/image.png?type=w800\"\r\n");
      out.write("						alt=\"place-name\">\r\n");
      out.write("					<div style=\"border: none;\">\r\n");
      out.write("						<h2>예약한 가게명</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"border: none;\">\r\n");
      out.write("						<h3>예약일시 / 예약 인원</h3>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"reserv-place-list\">\r\n");
      out.write("					<img src=\"https://kr.savorjapan.com/gg/content_image/t0283_017.jpg\"\r\n");
      out.write("						alt=\"place-name\">\r\n");
      out.write("					<div style=\"border: none;\">\r\n");
      out.write("						<h2>무라카미 하코다테 본점</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"border: none;\">\r\n");
      out.write("						<h3>2025.01.27 15:00 / 3명</h3>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"reserv-place-list\">\r\n");
      out.write("					<img src=\"https://kr.savorjapan.com/gg/content_image/t0283_005.jpg\"\r\n");
      out.write("						alt=\"place-name\">\r\n");
      out.write("					<div style=\"border: none;\">\r\n");
      out.write("						<h2>라멘 삿포로 이치류안</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"border: none;\">\r\n");
      out.write("						<h3>2025.01.11 19:00 / 1명</h3>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"reserv-place-list\">\r\n");
      out.write("					<img src=\"https://kr.savorjapan.com/gg/content_image/t0283_015.jpg\"\r\n");
      out.write("						alt=\"place-name\">\r\n");
      out.write("					<div style=\"border: none;\">\r\n");
      out.write("						<h2>해산물 로바타야키</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"border: none;\">\r\n");
      out.write("						<h3>2025.02.11 15:00 / 1명</h3>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<br> <br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"like-list\" style=\"border: none;\">\r\n");
      out.write("\r\n");
      out.write("				<h2 style=\"margin-inline-end: auto;\">좋아요한 가게</h2>\r\n");
      out.write("				<div style=\"border: none;\">\r\n");
      out.write("					<h3><a href=\"http://localhost/18_KHH_Test/LikeListPage.jsp\"> 더보기 ></a></h3>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<hr>\r\n");
      out.write("			<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"like-place-list-field\">\r\n");
      out.write("				<div class=\"like-place-list\">\r\n");
      out.write("					<img\r\n");
      out.write("						src=\"https://mblogthumb-phinf.pstatic.net/MjAxODA3MDVfNDAg/MDAxNTMwNzU3MjEyNjQ0.RNprD67cJ2AOWI2GmRVprWVv7qtNI-d3WsN-XhRLTLIg.hpd6lxFA6mkoZ-78fN-zmiLtxAv9H3iP_Jxs6bF7XCEg.PNG.witchstudio/image.png?type=w800\"\r\n");
      out.write("						alt=\"place-name\">\r\n");
      out.write("					<div style=\"border: none;\">\r\n");
      out.write("						<h2><span>🍴</span> 좋아한 가게명</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"like-place-list\">\r\n");
      out.write("					<img src=\"https://kr.savorjapan.com/gg/content_image/t0283_017.jpg\"\r\n");
      out.write("						alt=\"place-name\">\r\n");
      out.write("					<div style=\"border: none;\">\r\n");
      out.write("						<h2><span>🍴</span> 무라카미 하코다테 본점</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"like-place-list\">\r\n");
      out.write("					<img src=\"https://kr.savorjapan.com/gg/content_image/t0283_005.jpg\"\r\n");
      out.write("						alt=\"place-name\">\r\n");
      out.write("					<div style=\"border: none;\">\r\n");
      out.write("						<h2><span>🍴</span> 라멘 삿포로 이치류안</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"like-place-list\">\r\n");
      out.write("					<img src=\"https://kr.savorjapan.com/gg/content_image/t0283_015.jpg\"\r\n");
      out.write("						alt=\"place-name\">\r\n");
      out.write("					<div style=\"border: none;\">\r\n");
      out.write("						<h2><span>🍴</span> 해산물 로바타야키</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"footer\">footer</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
