/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2025-01-13 07:23:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ReservationPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/csj97/tomcat/lib/jstl-1.2.jar", Long.valueOf(1734052058125L));
    _jspx_dependants.put("jar:file:/C:/csj97/tomcat/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("/* 기본 스타일 */\r\n");
      out.write("* {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	font-family: 'Arial', 'Helvetica', 'Verdana', sans-serif; /* 고딕체 설정 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 컨테이너 설정 */\r\n");
      out.write(".container {\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	color: #000;\r\n");
      out.write("	width: 100vw; /* 전체 화면 너비 */\r\n");
      out.write("	height: 100vh; /* 전체 화면 높이 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 헤더 스타일 */\r\n");
      out.write(".header {\r\n");
      out.write("	height: 6vh; /* 화면 비율로 높이 설정 */\r\n");
      out.write("	background-color: #000;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	line-height: 6vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 네비게이션 바 스타일 */\r\n");
      out.write(".nav {\r\n");
      out.write("	height: 5vh; /* 화면 비율로 높이 설정 */\r\n");
      out.write("	background-color: #333;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	line-height: 5vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 콘텐츠 영역 */\r\n");
      out.write(".content {\r\n");
      out.write("	margin-top: 6vh;\r\n");
      out.write("	margin-left: 3vw;\r\n");
      out.write("	margin-right: 3vw;\r\n");
      out.write("	height: auto;\r\n");
      out.write("	border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 푸터 스타일 */\r\n");
      out.write(".footer {\r\n");
      out.write("	height: 10vh; /* 화면 비율로 높이 설정 */\r\n");
      out.write("	background-color: #000;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	line-height: 10vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 마이페이지 */\r\n");
      out.write(".mypage h1 {\r\n");
      out.write("	font-size: 2vw; /* 화면 너비에 비례한 글씨 크기 */\r\n");
      out.write("	color: #000;\r\n");
      out.write("\r\n");
      out.write("	margin: 1vh 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 좋아요한 가게 리스트 */\r\n");
      out.write(".reservation-list {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: flex-start;\r\n");
      out.write("	margin: 1vh 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reservation-list h2 {\r\n");
      out.write("	font-size: 1.5vw; /* 화면 너비에 비례한 글씨 크기 */\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	color: #000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 가게 리스트 스타일 */\r\n");
      out.write(".reserv-place-list-field {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: unset;\r\n");
      out.write("	border: 1px solid #ddd;\r\n");
      out.write("	margin-bottom: 1vh;\r\n");
      out.write("	padding: 2vh;\r\n");
      out.write("	background-color: #f7f7f7;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reserv-place-list {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reserv-place-list img {\r\n");
      out.write("	width: 18vw; /* 화면 너비의 18% 크기 */\r\n");
      out.write("	height: 18vw; /* 화면 너비의 18% 크기 */\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	margin-right: 3vw;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 가게 정보 텍스트 */\r\n");
      out.write(".reserv-place-list div {\r\n");
      out.write("	text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reserv-place-list h1 {\r\n");
      out.write("	font-size: 1.5vw; /* 화면 너비에 비례한 글씨 크기 */\r\n");
      out.write("	color: #000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reserv-place-list p {\r\n");
      out.write("	font-size: 0.9vw; /* 화면 너비에 비례한 글씨 크기 */\r\n");
      out.write("	color: #555;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 버튼 스타일 */\r\n");
      out.write("input[type=\"button\"] {\r\n");
      out.write("	background-color: #333;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	border: none;\r\n");
      out.write("	padding: 0.8vh 1.2vw; /* 화면 비례한 패딩 */\r\n");
      out.write("	font-size: 1vw; /* 화면 너비에 비례한 글씨 크기 */\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"button\"]:hover {\r\n");
      out.write("	background-color: #555;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 페이지 번호 */\r\n");
      out.write(".bottom-list-num {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin: 1vh 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bottom-list-num h2 {\r\n");
      out.write("	font-size: 1.5vw; /* 화면 너비에 비례한 글씨 크기 */\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	color: #000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 돌아가기 버튼 */\r\n");
      out.write(".bottom-return-btn {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin-top: 1vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bottom-return-btn input[type=\"button\"] {\r\n");
      out.write("	background-color: #000;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	padding: 1vh 2vw;\r\n");
      out.write("	font-size: 1vw;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bottom-return-btn input[type=\"button\"]:hover {\r\n");
      out.write("	background-color: #444;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 프로필 스타일 */\r\n");
      out.write(".profile-field {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile-circle img {\r\n");
      out.write("	border-radius: 50%;\r\n");
      out.write("	width: 10vw; /* 화면 너비의 10% 크기 */\r\n");
      out.write("	height: 10vw; /* 화면 너비의 10% 크기 */\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"header\">header</div>\r\n");
      out.write("		<div class=\"nav\">nav</div>\r\n");
      out.write("		<div class=\"content\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"mypage\" style=\"border: none;\">\r\n");
      out.write("				<h1>MyPage (누르면 마이페이지 메인으로 이동)</h1>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br>\r\n");
      out.write("			<hr>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"reservation-list\" style=\"border: none;\">\r\n");
      out.write("				<h2 style=\"margin-inline-end: auto;\">예약한 가게</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"reserv-place-list-field\" style=\"border: solid 1px;\">\r\n");
      out.write("				<div class=\"reserv-place-list\">\r\n");
      out.write("					<img\r\n");
      out.write("						src=\"https://mblogthumb-phinf.pstatic.net/MjAxODA3MDVfNDAg/MDAxNTMwNzU3MjEyNjQ0.RNprD67cJ2AOWI2GmRVprWVv7qtNI-d3WsN-XhRLTLIg.hpd6lxFA6mkoZ-78fN-zmiLtxAv9H3iP_Jxs6bF7XCEg.PNG.witchstudio/image.png?type=w800\"\r\n");
      out.write("						alt=\"place-name\">\r\n");
      out.write("					<div style=\"border: none; text-align: left; margin-left: 30px\">\r\n");
      out.write("						<h1>\r\n");
      out.write("							<span>😋</span>예약한 가게명\r\n");
      out.write("							<br>\r\n");
      out.write("							예약일시 / 예약인원\r\n");
      out.write("						</h1>\r\n");
      out.write("						<div style=\"border: none;\">\r\n");
      out.write("							<h2>가게 상세주소</h2>\r\n");
      out.write("							<p	>영업시간</p>\r\n");
      out.write("							<p>예약자 이름 : 000</p>\r\n");
      out.write("							<p>예약자 전화번호 : 000</p>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div style=\"border: none; align-content: center; margin-left: 80px;\">\r\n");
      out.write("					<input type=\"button\" value=\"가게 정보 보기\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"reserv-place-list-field\" style=\"border: solid 1px;\">\r\n");
      out.write("				<div class=\"reserv-place-list\">\r\n");
      out.write("					<img src=\"https://kr.savorjapan.com/gg/content_image/t0283_005.jpg\"\r\n");
      out.write("						alt=\"place-name\">\r\n");
      out.write("					<div style=\"border: none; text-align: left; margin-left: 30px\">\r\n");
      out.write("							<h1>\r\n");
      out.write("							<span>😋</span>예약한 가게명\r\n");
      out.write("							<br>\r\n");
      out.write("							예약일시 / 예약인원\r\n");
      out.write("						</h1>\r\n");
      out.write("						<div style=\"border: none;\">\r\n");
      out.write("							<h2>가게 상세주소</h2>\r\n");
      out.write("							<p	>영업시간</p>\r\n");
      out.write("							<p>예약자 이름 : 000</p>\r\n");
      out.write("							<p>예약자 전화번호 : 000</p>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			<div style=\"border: none; align-content: center; margin-left: 80px;\">\r\n");
      out.write("					<input type=\"button\" value=\"가게 정보 보기\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"reserv-place-list-field\" style=\"border: solid 1px;\">\r\n");
      out.write("				<div class=\"reserv-place-list\">\r\n");
      out.write("					<img src=\"https://kr.savorjapan.com/gg/content_image/t0283_005.jpg\"\r\n");
      out.write("						alt=\"place-name\">\r\n");
      out.write("					<div style=\"border: none; text-align: left; margin-left: 30px\">\r\n");
      out.write("						<h1>\r\n");
      out.write("							<span>😋</span>예약한 가게명\r\n");
      out.write("							<br>\r\n");
      out.write("							예약일시 / 예약인원\r\n");
      out.write("						</h1>\r\n");
      out.write("						<div style=\"border: none;\">\r\n");
      out.write("							<h2>가게 상세주소</h2>\r\n");
      out.write("							<p	>영업시간</p>\r\n");
      out.write("							<p>예약자 이름 : 000</p>\r\n");
      out.write("							<p>예약자 전화번호 : 000</p>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			<div style=\"border: none; align-content: center; margin-left: 80px;\">\r\n");
      out.write("					<input type=\"button\" value=\"가게 정보 보기\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"reserv-place-list-field\" style=\"border: solid 1px;\">\r\n");
      out.write("				<div class=\"reserv-place-list\">\r\n");
      out.write("					<img src=\"https://kr.savorjapan.com/gg/content_image/t0283_015.jpg\"\r\n");
      out.write("						alt=\"place-name\">\r\n");
      out.write("					<div style=\"border: none; text-align: left; margin-left: 30px\">\r\n");
      out.write("								<h1>\r\n");
      out.write("							<span>😋</span>예약한 가게명\r\n");
      out.write("							<br>\r\n");
      out.write("							예약일시 / 예약인원\r\n");
      out.write("						</h1>\r\n");
      out.write("						<div style=\"border: none;\">\r\n");
      out.write("							<h2>가게 상세주소</h2>\r\n");
      out.write("							<p	>영업시간</p>\r\n");
      out.write("							<p>예약자 이름 : 000</p>\r\n");
      out.write("							<p>예약자 전화번호 : 000</p>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			<div style=\"border: none; align-content: center; margin-left: 80px;\">\r\n");
      out.write("					<input type=\"button\" value=\"가게 정보 보기\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<br> <br>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"bottom-list-num\" style=\"border: none;\">\r\n");
      out.write("				<h2>1 2 3 4 (나중에 구현) ></h2>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"bottom-return-btn\"\r\n");
      out.write("				style=\"border: none; align-content: center;\">\r\n");
      out.write("				<input type=\"button\" value=\"마이페이지로 돌아가기\">\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"footer\">footer</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
