/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2025-01-10 06:40:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ReviewPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/csj97/tomcat/lib/jstl-1.2.jar", Long.valueOf(1734052058125L));
    _jspx_dependants.put("jar:file:/C:/csj97/tomcat/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("div {\r\n");
      out.write("	border: 1px solid;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header {\r\n");
      out.write("	height: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav {\r\n");
      out.write("	height: 70px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content {\r\n");
      out.write("	margin-top: 100px;\r\n");
      out.write("	margin-left: 100px;\r\n");
      out.write("	margin-right: 100px;\r\n");
      out.write("	height: 3500px;\r\n");
      out.write("	border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer {\r\n");
      out.write("	height: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile-field {\r\n");
      out.write("	display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile-circle img {\r\n");
      out.write("	border-radius: 50%;\r\n");
      out.write("	width: 170px;\r\n");
      out.write("	height: 170px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".review-list {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: flex-end;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".review-comment {\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	font-weight: bolder;\r\n");
      out.write("	color: dark-grey;\r\n");
      out.write("	display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reservation-list {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: flex-end;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".like-list {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: flex-end;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".like-place-list {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".like-place-list img {\r\n");
      out.write("	width: 300px;\r\n");
      out.write("	height: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".like-place-list-field {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reserv-place-list {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	border: none;\r\n");
      out.write("	margin: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reserv-place-list img {\r\n");
      out.write("	width: 300px;\r\n");
      out.write("	height: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reserv-place-list-field {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bottom-list-num {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	item-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text-box{\r\n");
      out.write("margin-top: 20px;\r\n");
      out.write("margin-left: 20px;\r\n");
      out.write("margin-bottom: 40px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"header\">header</div>\r\n");
      out.write("		<div class=\"nav\">nav</div>\r\n");
      out.write("		<div class=\"content\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"mypage\" style=\"border: none;\">\r\n");
      out.write("				<h1>MyPage</h1>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br>\r\n");
      out.write("			<hr>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"reservation-list\" style=\"border: none;\">\r\n");
      out.write("				<h2 style=\"margin-inline-end: auto;\">예약한 가게</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"reserv-place-list-field\" style=\"border: solid 1px;\">\r\n");
      out.write("				<div class=\"reserv-place-list\">\r\n");
      out.write("					<img\r\n");
      out.write("						src=\"https://mblogthumb-phinf.pstatic.net/MjAxODA3MDVfNDAg/MDAxNTMwNzU3MjEyNjQ0.RNprD67cJ2AOWI2GmRVprWVv7qtNI-d3WsN-XhRLTLIg.hpd6lxFA6mkoZ-78fN-zmiLtxAv9H3iP_Jxs6bF7XCEg.PNG.witchstudio/image.png?type=w800\"\r\n");
      out.write("						alt=\"place-name\">\r\n");
      out.write("					<div style=\"border: none;\">\r\n");
      out.write("						<h2>예약한 가게명</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"border: none;\">\r\n");
      out.write("						<h2>예약일시 / 예약 인원</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"text-box\" style=\"border: none;\">\r\n");
      out.write("\r\n");
      out.write("					예약한 가게명\r\n");
      out.write("					가게 상세주소 \r\n");
      out.write("					예약일시\r\n");
      out.write("					예약인원\r\n");
      out.write("					예약자 이름 : 000  예약자 전화번호 : 000  \r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"reserv-place-list-field\" style=\"border: solid 1px;\">\r\n");
      out.write("				<div class=\"reserv-place-list\">\r\n");
      out.write("					<img src=\"https://kr.savorjapan.com/gg/content_image/t0283_017.jpg\"\r\n");
      out.write("						alt=\"place-name\">\r\n");
      out.write("					<div style=\"border: none;\">\r\n");
      out.write("						<h2>무라카미 하코다테 본점</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"border: none;\">\r\n");
      out.write("						<h2>2025.01.27 15:00 / 3명</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"reserv-place-list-field\" style=\"border: solid 1px;\">\r\n");
      out.write("				<div class=\"reserv-place-list\">\r\n");
      out.write("					<img src=\"https://kr.savorjapan.com/gg/content_image/t0283_005.jpg\"\r\n");
      out.write("						alt=\"place-name\">\r\n");
      out.write("					<div style=\"border: none;\">\r\n");
      out.write("						<h2>라멘 삿포로 이치류안</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"border: none;\">\r\n");
      out.write("						<h2>2025.01.11 19:00 / 1명</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"reserv-place-list-field\" style=\"border: solid 1px;\">\r\n");
      out.write("				<div class=\"reserv-place-list\">\r\n");
      out.write("					<img src=\"https://kr.savorjapan.com/gg/content_image/t0283_015.jpg\"\r\n");
      out.write("						alt=\"place-name\">\r\n");
      out.write("					<div style=\"border: none;\">\r\n");
      out.write("						<h2>해산물 로바타야키</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"border: none;\">\r\n");
      out.write("						<h2>2025.02.11 15:00 / 1명</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<br> <br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"footer\">footer</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
